[package]
name = "bevy_services"
version = "0.1.0"
edition = "2021"
authors = ["Grey <mxgrey@intrinsic.ai>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
arrayvec = "*"
smallvec = "*"
