[package]
name = "bevy_impulse"
version = "0.0.1"
edition = "2021"
authors = ["Grey <mxgrey@intrinsic.ai>"]

[dependencies]
bevy_ecs = "0.12"
bevy_tasks = { version = "0.12", features = ["multi-threaded"] }
bevy_utils = "0.12"
bevy_hierarchy = "0.12"
bevy_derive = "0.12"
bevy_app = "0.12"

arrayvec = "*"
itertools = "*"
smallvec = "*"
crossbeam = "*"
futures = "0.3"
backtrace = "0.3"
anyhow = "*"
thiserror = "*"

# These dependencies are only used by the testing module.
# We may want to consider feature-gating them, but we use
# the testing module for doctests, and doctests can only
# make use of default features, so we're a bit stuck with
# these for now.
bevy_core = "0.12"
bevy_time = "0.12"

[dev-dependencies]
async-std = { version = "*" }
