[package]
name = "bevy_impulse"
version = "0.0.1"
edition = "2021"
authors = ["Grey <mxgrey@intrinsic.ai>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
arrayvec = "*"
smallvec = "*"
crossbeam = "*"
futures = "0.3"
backtrace = "0.3"

[dev-dependencies]
async-std = { version = "*" }
