[package]
name = "bevy_impulse"
version = "0.0.1"
edition = "2021"
authors = ["Grey <mxgrey@intrinsic.ai>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.12"
bevy_tasks = { version = "0.12", features = ["multi-threaded"] }
bevy_utils = "0.12"
bevy_hierarchy = "0.12"
bevy_derive = "0.12"
bevy_app = "0.12"

arrayvec = "*"
itertools = "*"
smallvec = "*"
crossbeam = "*"
futures = "0.3"
backtrace = "0.3"
anyhow = "*"
thiserror = "*"

[dev-dependencies]
async-std = { version = "*" }
bevy = "0.12"
